google:
  project: my-project
  region: eu-west-1

tenant: 123456
create:
  vpc: true
  cloudRouter: false

vpc:
  name: ${google_compute_network.network.name}
#  cloudRouter:
#    name: "test"

clusterName: test-namespace

networks:
  cloudNAT:
    minPortsPerVM: 2048
#   natIPNames: ["manualnat1", "manualnat2"]
  services: 100.64.0.0/13
  pods: 100.96.0.0/11
  workers: 10.250.0.0/19
# internal: 10.250.112.0/22
# flowLogs:
#   aggregationInterval: "INTERVAL_10_MIN"
#   flowSampling: 0.2
#   metadata: "INCLUDE_ALL_METADATA"

outputKeys:
  vpcName: vpc_name
  cloudNAT: cloud_nat
  natIPs: nat_ips
  cloudRouter: cloud_router
  subnetNodes: subnet_nodes
  serviceAccountEmail: service_account_email
  subnetInternal: subnet_internal
